# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: ##NAMESPACE##

generatorOptions:
  disableNameSuffixHash: true

# list of Resource Config to be Applied
resources:
  - channel.yaml
  - subscription.yaml

patches:
- path: dir_patch.json
  target:
    version: v1
    kind: ConfigMap
    name: policies-github-path